# Generated by Django 6.0.6 on 2026-07-02 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_status', models.CharField(choices=[('idle', 'Idle'), ('walking', 'Walking'), ('falling', 'Falling')], default='idle', max_length=20)),
                ('heart_rate', models.FloatField()),
                ('spo2', models.FloatField()),
                ('temperature', models.FloatField()),
                ('mq135', models.FloatField(default=0.0)),
                ('mq2', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
