# Generated by Django 6.0.6 on 2026-08-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='motion_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('fall_detected', 'Fall Detected')], default='normal', max_length=20),
        ),
    ]
