# Generated by Django 6.0.6 on 2026-08-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sensorreading_motion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='mq135_normalized',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='mq2_normalized',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
