# Generated by Django 6.0.6 on 2026-08-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sensorreading_mq135_normalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='spo2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
